# see: github.com/dwyl/learn-travis
language: elixir
elixir:
  - 1.4.1
services:
  - elasticsearch
env:
  - MIX_ENV=test
script:
  - mix do deps.get, compile --warnings-as-errors, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
